spring.application.name=sentinel-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel
spring.datasource.username=postgres
spring.datasource.password=ananya@2469

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info