spring.application.name=sentinel-backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sentinel}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_passwd}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info